# This is a basic workflow to help deploy an armory project on Itch.io

name: Itch.io Deploy Workflow

# Controls when the workflow will run
on:
  workflow_run:
    workflows: [github-deploy]
    types: [completed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  itchio-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
    - uses: KikimoraGames/itch-publish@v0.0.3
      with:
         butlerApiKey: ${{secrets.ITCH_IO_API_KEY}}
         gameData: html5
         itchUsername: quantumcoderqc
         itchGameId: armory3d-lava-lamp
         buildChannel: html
         buildNumber: 1
