# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  #Allows for re-usable actions
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
      - name: Install blender
        run: sudo snap install blender --channel=3.3lts/stable --classic
      - name: Install armsdk
        run: |
          git clone --recurse-submodules https://github.com/armory3d/armsdk.git
          git clone --recurse-submodules https://github.com/QuantumCoderQC/ArmoryBuildFilesGH.git
          blender -noaudio -b -P ArmoryBuildFilesGH/enable_addon.py
      - name: Build examples
        run: |
          haxe ArmoryBuildFilesGH/build-examples.hxml
      - name: Deploy gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: web
          clean: true
